### ISSUE TITLE
Implement `exists_function` resolution using `fsspec` in `SparkDataSet`

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro-plugins#117]
## Description
The `exists_function` is used by `AbstractVersionedDataSet` to resolve the path to a stored, versioned dataset. In other dataset implementations, the `exists_function` is set to fsspec.filesystem(...)._fs.exists. In `SparkDataSet`, we have a complex series of logical tests to determine the `exists_function`, this is brittle (as every possible file system in use has to be anticipated a priori) and a source of error (as in https://github.com/kedro-org/kedro/issues/1801).

## Context
`SparkDataSet` sees high use, making this change would eliminate a source of bugs in a dataset that is important to our users.

**Comment by noklam** [comment]
Development notes: (Continue to update)
* Tried `DatabricksFileSystem` - `from fsspec.implementations.dbfs import DatabricksFileSystem`
This could work in theory and you can pass the `token` as `credentials`. However it isn't that useful since you almost always run on **Databricks**, therefore you don't really want to authenticate via a token. This will be only useful when you try to access `dbfs` while you are running a program outside of **Databricks**.

**Comment by noklam** [comment]
To summarise the current issue:

1. When `dbfs/` not include in path:
* Spark will always add `dbfs/` prefix
* `_fetch_latest_version` will use `os` library, by default it doesn't use the `dbfs` as root - as a result it can't find the file because Spark saved it in `dbfs/xxxx`

This is why when `versioned: True` + `dbfs/` not used in the filepath it cannot load the data successfully.

2. When `/dbfs` is included in path:
`kedro` strip the "dbfs" in the dataset - When using Spark it adds the `dbfs/` prefix
* DataSet get saved in `dbfs/filepath`
* `_fetch_latest_version` using os.glob("dbfs/filepath") - finding the correct version

Alternative:
Using `dbfs://` like `gcs`, `s3` instead of `dbfs/`
* This would be ideal if `fsspec` already handle it, but it doesn't
* It really only affect Spark, so conditioning in Spark seems inevitable to me.

We can potentially remove this block of condition and just let `fsspec` do the work

```python
        if fs_prefix in ("s3a://", "s3n://"):
            if fs_prefix == "s3n://":
                warn(
                    "'s3n' filesystem has now been deprecated by Spark, "
                    "please consider switching to 's3a'",
                    DeprecationWarning,
                )
            _s3 = S3FileSystem(**credentials)
            exists_function = _s3.exists
            glob_function = partial(_s3.glob, refresh=True)
            path = PurePosixPath(filepath)
```

@AntonyMilneQB  @jmholzer
