### ISSUE TITLE
Xarray NetCDFDataSet

### ISSUE THREAD

**Issue by lucasjamar** [kedro-org/kedro-plugins#165]
## Description
Read and write netcdf file into Xarray.
https://xarray.pydata.org/en/stable/user-guide/io.html#netcdf

## Context
Should attract the weather data science community to use kedro :)

## Possible Implementation
Should be quite similar to pandas.CSVDataSet. I'll give this implementation a shot in my free time.

Has anyone ever implemented such a custom dataset already?

**Comment by astrojuanlu** [comment]
Talking to some folks working with satellite data, would be cool to have this 🛰️

**Comment by riley-brady** [comment]
Looking to open a PR on this in the next week or so.

**Comment by noklam** [comment]
@riley-brady that's awesome!

**Comment by galenseilis** [comment]
> Looking to open a PR on this in the next week or so.

As a PyMC user I am excited by this news!

**Comment by riley-brady** [comment]
Glad to see the excitement! I'm bundling it with a Zarr implementation, since those are commonly used together. We've got a nicely working implementation on our climate team for both, targeting an AWS platform. Let's start with stripping it down to a local-working implementation and then see how we can build it up from there.

Zarr should work out of the box for remote read/write. NetCDF can't be read remotely natively (e.g. from an S3 bucket), so we pull it down to temp storage and then do the read. One could also do something like a `kerchunk` wrapper to generalize remote reads for NetCDF.

**Comment by noklam** [comment]
I talked to @tgoelles today and he is interested to contribute a dataset for geotiff and NetCDF. I am excited to see more contributions from the scientific community🔥

**Comment by tgoelles** [comment]
@noklam I implemented geotiff for now but the build on github actions fails for windows du to the dependency on GDAL

Collecting rasterio (from rioxarray>=0.9.0->kedro-datasets==1.7.0)
  Downloading rasterio-1.2.10.tar.gz (2.3 MB)
     ---------------------------------------- 2.3/2.3 MB 36.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [2 lines of output]
  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
  [end of output]

Is there a way to support geotiff only for Ubuntu for now? I don't want to look into windows issues, and I know that GDAL makes installations complex

**Comment by astrojuanlu** [comment]
I can help with GDAL on Windows 👍🏽 go ahead and open the PR!

**Comment by KikiCS** [comment]
I'm also really looking forward to this PR!

**Comment by riley-brady** [comment]
Hi folks! I put a decent stake in the ground here: https://github.com/kedro-org/kedro-plugins/pull/360/files. There's a few TODO's to deal with at the moment.

I have some pressing work deadlines I need to focus on so I might not get back to this for a couple of weeks. But wanted to provide the initial snippet for folks to test out/provide feedback on instead of going silent here.

I'd like to get this implemented with file syncing for load-from-remote, since it's most straight-forward. A future PR could work with [kerchunk](https://fsspec.github.io/kerchunk/) to allow direct loading from remote storage. This is a really nice toolkit, but requires management of a lot of JSON metadata files that are generated, and which sometimes can be quite slow to generate. It will take a little bit of tweaking to implement this nicely, since the first run would need to generate and cache/store all of the reference JSONs to make future loads much much faster.

**Comment by riley-brady** [comment]
Hi everyone! The PR is fully implemented with testing and ready for review. https://github.com/kedro-org/kedro-plugins/pull/360

**Comment by astrojuanlu** [comment]
Of interest for people subscribed to this issue: https://guide.cloudnativegeo.org ([source](https://cloudnativegeo.org/blog/2023/10/introducing-the-cloud-optimized-geospatial-formats-guide/))

![image](https://github.com/kedro-org/kedro-plugins/assets/316517/7bf4fcd0-93c5-4799-8446-5f821190dd8b)

**Comment by riley-brady** [comment]
I think this can be closed via https://github.com/kedro-org/kedro-plugins/pull/360!

**Comment by astrojuanlu** [comment]
Closed in #360 indeed! 🚀
