### ISSUE TITLE
Resolve Python Version for Linting in kedro-plugins

### ISSUE THREAD

**Issue by SajidAlamQB** [kedro-org/kedro-plugins#317]
## Description

There's an inconsistency in the Python version used for linting across the different kedro plugins in our GitHub actions files. The original version for linting in `kedro-plugins` was 3.8. However, with `kedro-datasets` [adopting python 3.11](https://github.com/kedro-org/kedro-plugins/pull/297), there's a discussion about whether it makes sense to align the linting version to 3.11, even if other plugins don't support it.

## Current Issue:

Attempting to lint with Python 3.11 results in a `ResolutionTooDeep` error for airflow and docker. The error details are:

```
raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
```

This seems to indicate dependency resolution issues. As a temporary solution in https://github.com/kedro-org/kedro-plugins/pull/297, linting for `kedro-datasets` runs on 3.11 while other plugins continue with 3.8.

## Potential Solutions:

- Streamline linting dependencies across plugins.

- Integrate linting configurations into pre-commit to ensure that linters operate in consistent isolated environments across plugins.

- @noklam suggested that a longer-term solution might be migrating to ruff, which could alleviate some of these issues. https://github.com/kedro-org/kedro-plugins/pull/311

**Comment by noklam** [comment]
Noted that this may be a dependency issue, because we have different pin of `black`,`flake` etc.

So:
- https://github.com/kedro-org/kedro-plugins/pull/311
- Or align and relax the dependencies

For Linting itself, it should even require `airflow` to be installed. IMO settle this in `pre-commit` which comes with it on virtuanenv is the best way to solve this, then we can remove all linting dependencies from `.[test]`.

**Comment by merelcht** [comment]
Closing in favour of https://github.com/kedro-org/kedro-plugins/issues/320
