### ISSUE TITLE
Decide on the best place to publish information about `kedro-telemetry` to our users

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-plugins#509]
## Description
A lot of open-source projects will detail their telemetry collection practices in their documentation. This task is to consult @stichbury about the best placement of our information about `kedro-telemetry`. Do we leave it on the README.md or move this document to our documentation so it's more visible for users?

**Comment by stichbury** [comment]
I think this is probably a case of "_Why not both?_". I think it would make sense to have a better coverage of telemetry in the main docs (this could be in the plugins section perhaps) and link that through to the README. 

I would not put any more in the [first place telemetry is mentioned](https://docs.kedro.org/en/stable/get_started/new_project.html) since that's getting in the way of most new users creating a first project, but instead possibly put a description in the glossary or a section in the plugins docs (which need some work anyway, so we could make better sections for Kedro-team maintained plugins like telemetry). This would summarise briefly but use the README as the main resource.

**Comment by astrojuanlu** [comment]
I support adding this to our docs _on top of_ the README, which is what most other projects do https://github.com/kedro-org/kedro-plugins/issues/510#issuecomment-1885237973

**Comment by astrojuanlu** [comment]
Also, the current link https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry#privacy-notice is broken (it lands on the README but there's no "privacy notice" header anymore). We need a more permanent place for this.

> I think it would make sense to have a better coverage of telemetry in the main docs (this could be in the plugins section perhaps) and link that through to the README.

I'm +1 on this. Any objections @merelcht @rashidakanchwala @NeroOkwa ? (So that we can log the _decision_)

**Comment by astrojuanlu** [comment]
I'll take that as a yes. Let's place this information on https://docs.kedro.org/.

**Comment by stichbury** [comment]
In closing this, I'll assume you're ticketing the work itself separately.

**Comment by astrojuanlu** [comment]
Yep, #508
