### ISSUE TITLE
`kedro-telemetry` causes error in read-only environments

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-plugins#781]
## Description
Details still TBC, but there are hints that `kedro-telemetry>=0.3.1` can produce an error when running on a read-only environment.

## Context
https://linen-slack.kedro.org/t/22727587/hi-everyone-i-am-new-to-kedro-and-i-am-wondering-how-we-can-#66d97df5-5f59-4c93-a9f1-f68b5cef416f

The user was trying to run a pipeline on Google App Engine like this:

```python
from kedro.framework.session import KedroSession
from kedro.framework.startup import bootstrap_project
from pathlib import Path
bootstrap_project(Path.cwd())
with KedroSession.create(save_on_close=False) as session:
    session.run()
```

(Following this link: https://docs.kedro.org/en/stable/kedro_project_setup/session.html)

cc @oscarvilla

**Comment by ElenaKhaustova** [comment]
Reached out to the user to get some details.

**Comment by oscarvilla** [comment]
For completeness, I'm running the pipeline just with ```kedro run```.

And when I remove telemetry from the requirements.txt passed into the App Engine builder/deployer, the read-only error disappears.

**Comment by ElenaKhaustova** [comment]
Thank you, @oscarvilla!

Some additional context:

1. The user sees a `log.error` message that we output, but the error itself is caught, so it does not affect the execution 
2. That's the expected behaviour for read-only environments; here is how we handle it: https://github.com/kedro-org/kedro-plugins/blob/24cd01c23dc36145ff7893f5497df86960a0f68f/kedro-telemetry/kedro_telemetry/plugin.py#L112
3. In this case, `project_id` is considered as not set

It doesn't look like any immediate fixes are required, but we can consider the following:

1. Change the log lever from error to warning so it doesn't look scary to users.
2. Show it only once for read-only environments now we log it every time we collect the telemetry
3. Do not show it to users at all but log it at telemetry, so we know it's a read-only environment

**Comment by astrojuanlu** [comment]
Agreed with all the points @ElenaKhaustova !

**Comment by merelcht** [comment]
Also flagged by a user: https://github.com/kedro-org/kedro/issues/4066
