### ISSUE TITLE
`kedro-telemetry`: Environment var do not override the consent from the `.telemetry` if not command run case

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro-plugins#785]
## Description
Relates to https://github.com/kedro-org/kedro-plugins/pull/762 and https://github.com/kedro-org/kedro/issues/4024

## Context
We call `_check_for_telemetry_consent` before each command run. However, in the rest of the cases, we call `_check_for_telemetry_consent` after the context is created but we also check if `self._consent` was not set: https://github.com/kedro-org/kedro-plugins/blob/24cd01c23dc36145ff7893f5497df86960a0f68f/kedro-telemetry/kedro_telemetry/plugin.py#L209

It makes it impossible to override the consent from the `.telemetry` by setting the environment variable (`"DO_NOT_TRACK"` or `"KEDRO_DISABLE_TELEMETRY"`) for example in interactive environments.

## Steps to Reproduce
1. create `.telemetry` with `consent: true`
2. `kedro ipython`
3. consent in `.telemetry` is set to true, telemetry is sent (as expected}
4. set `os.environ["DO_NOT_TRACK"] = "true"`
5. `%reload_ext kedro.ipython`
6. consent in `.telemetry` is set to true, `os.environ["DO_NOT_TRACK"]` is true, telemetry is still sent (not expected)

The same issue if changing `.telemetry` in interactive environment:
1. create `.telemetry` with `consent: true`
2. `kedro ipython`
3. consent in `.telemetry` is set to true, telemetry is sent (as expected}
4. update `.telemetry` with `consent: false`
5. `%reload_ext kedro.ipython`
6. consent in `.telemetry` is set to false, telemetry is still sent (not expected)

**Comment by lrcouto** [comment]
On https://github.com/kedro-org/kedro-plugins/pull/791 I tried to change the after_context_created hook to always set `self._consent` insead of only when it's None. It stops further unwanted calls every time we reload IPython with the DO_NOT_TRACK variable set. However, it still sends info to heap after the IPython shell is exited.

If you edit the .telemetry file itself inside IPython, it still sends info to heap once, because when the command was first called consent was true. I think this is a weird behavior. I'm looking into it further.
